{{ $ca := genCA "kube-oidc-proxy CA" 3650 }}
{{ $cert := genSignedCert "kube-oidc-proxy" (list) (list) 3650 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  ca.key: {{ $ca.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc}}
  tls.key: {{ $cert.Key | b64enc }}
